In [459]:
import pandas as pd
import numpy as np

In [500]:
df = pd.read_csv('each_ball_records.csv')

In [501]:
df['batsman_score'] = pd.to_numeric(df.outcome, errors='coerce')
df['1s'] = (df['outcome'] == '1').astype('int')
df['2s'] = (df['outcome'] == '2').astype('int')
df['3s'] = (df['outcome'] == '3').astype('int')
df['4s'] = (df['outcome'] == '4').astype('int')
df['6s'] = (df['outcome'] == '6').astype('int')
df['w'] = (df['outcome'] == 'w').astype('int')

In [502]:
def wide(y):
    return y.str.contains('wd')
def noball(z):
    return z.str.contains('nb')

In [503]:
df['wd'] = wide(df['outcome']).astype('int')
df['nb'] = noball(df['outcome']).astype('int')

In [504]:
df.tail()

,match_no,ballnumber,inningno,over,outcome,batter,bowler,comment,score,batsman_score,1s,2s,3s,4s,6s,w,wd,nb
17853,74,90,2,14.2,1,Shivam Dube,Mohit Sharma,"Mohit Sharma to Shivam Dube, 1 run,",1,1.0,1,0,0,0,0,0,0,0
17854,74,91,2,14.3,1,Ravindra Jadeja,Mohit Sharma,"Mohit Sharma to Ravindra Jadeja, 1 run,",1,1.0,1,0,0,0,0,0,0,0
17855,74,92,2,14.4,1,Shivam Dube,Mohit Sharma,"Mohit Sharma to Shivam Dube, 1 run,",1,1.0,1,0,0,0,0,0,0,0
17856,74,93,2,14.5,6,Ravindra Jadeja,Mohit Sharma,"Mohit Sharma to Ravindra Jadeja, Six,",6,6.0,0,0,0,0,1,0,0,0
17857,74,94,2,14.6,4,Ravindra Jadeja,Mohit Sharma,"Mohit Sharma to Ravindra Jadeja, Four,",4,4.0,0,0,0,1,0,0,0,0

In [509]:
df1 = pd.read_csv('each_match_records.csv')

In [510]:
df1.head()

,season,date,match_number,match_type,venue,location,team1,team2,toss_won,toss_decision,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,man_of_match
0,2023,31-03-2023,1,Group,Narendra Modi Stadium,Ahmedabad,Chennai Super Kings,Gujarat Titans,Gujarat Titans,field,Nitin Menon,HAS Khalid,A Bengeri,J Srinath,Gujarat Titans,NaN,5.0,Rashid Khan
1,2023,01-04-2023,2,Group,Punjab Cricket Association IS Bindra Stadium,Chandigarh,Punjab Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,BNJ Oxenford,YC Barde,PM Joshi,M Nayyar,Punjab Kings,7.0,NaN,Arshdeep Singh
2,2023,01-04-2023,3,Group,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Lucknow Super Giants,Delhi Capitals,Delhi Capitals,field,AK Chaudhary,NA Patwardhan,M Kuppuraj,DS Manohar,Lucknow Super Giants,50.0,NaN,MA Wood
3,2023,02-04-2023,4,Group,Rajiv Gandhi International Stadium,Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,KN Ananthapadmanabhan,R Pandit,Abhijit Bhattacharya,V Narayan Kutty,Rajasthan Royals,72.0,NaN,JC Buttler
4,2023,02-04-2023,5,Group,M Chinnaswamy Stadium,Bengaluru,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Nitin Menon,Tapan Sharma,A Bengeri,J Srinath,Royal Challengers Bangalore,NaN,8.0,F du Plessis

In [511]:
df1= df1.rename(columns={'match_number':'match_no'},inplace = False)
df1.head()

,season,date,match_no,match_type,venue,location,team1,team2,toss_won,toss_decision,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,man_of_match
0,2023,31-03-2023,1,Group,Narendra Modi Stadium,Ahmedabad,Chennai Super Kings,Gujarat Titans,Gujarat Titans,field,Nitin Menon,HAS Khalid,A Bengeri,J Srinath,Gujarat Titans,NaN,5.0,Rashid Khan
1,2023,01-04-2023,2,Group,Punjab Cricket Association IS Bindra Stadium,Chandigarh,Punjab Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,BNJ Oxenford,YC Barde,PM Joshi,M Nayyar,Punjab Kings,7.0,NaN,Arshdeep Singh
2,2023,01-04-2023,3,Group,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Lucknow Super Giants,Delhi Capitals,Delhi Capitals,field,AK Chaudhary,NA Patwardhan,M Kuppuraj,DS Manohar,Lucknow Super Giants,50.0,NaN,MA Wood
3,2023,02-04-2023,4,Group,Rajiv Gandhi International Stadium,Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,KN Ananthapadmanabhan,R Pandit,Abhijit Bhattacharya,V Narayan Kutty,Rajasthan Royals,72.0,NaN,JC Buttler
4,2023,02-04-2023,5,Group,M Chinnaswamy Stadium,Bengaluru,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Nitin Menon,Tapan Sharma,A Bengeri,J Srinath,Royal Challengers Bangalore,NaN,8.0,F du Plessis

In [512]:
merged_df = pd.merge(df, df1, on='match_no', how='inner')
merged_df.tail()

,match_no,ballnumber,inningno,over,outcome,batter,bowler,comment,score,batsman_score,...,toss_won,toss_decision,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,man_of_match
17853,74,90,2,14.2,1,Shivam Dube,Mohit Sharma,"Mohit Sharma to Shivam Dube, 1 run,",1,1.0,...,Chennai Super Kings,field,Nitin Menon,RJ Tucker,J Madanagopal,J Srinath,Chennai Super Kings,NaN,5.0,DP Conway
17854,74,91,2,14.3,1,Ravindra Jadeja,Mohit Sharma,"Mohit Sharma to Ravindra Jadeja, 1 run,",1,1.0,...,Chennai Super Kings,field,Nitin Menon,RJ Tucker,J Madanagopal,J Srinath,Chennai Super Kings,NaN,5.0,DP Conway
17855,74,92,2,14.4,1,Shivam Dube,Mohit Sharma,"Mohit Sharma to Shivam Dube, 1 run,",1,1.0,...,Chennai Super Kings,field,Nitin Menon,RJ Tucker,J Madanagopal,J Srinath,Chennai Super Kings,NaN,5.0,DP Conway
17856,74,93,2,14.5,6,Ravindra Jadeja,Mohit Sharma,"Mohit Sharma to Ravindra Jadeja, Six,",6,6.0,...,Chennai Super Kings,field,Nitin Menon,RJ Tucker,J Madanagopal,J Srinath,Chennai Super Kings,NaN,5.0,DP Conway
17857,74,94,2,14.6,4,Ravindra Jadeja,Mohit Sharma,"Mohit Sharma to Ravindra Jadeja, Four,",4,4.0,...,Chennai Super Kings,field,Nitin Menon,RJ Tucker,J Madanagopal,J Srinath,Chennai Super Kings,NaN,5.0,DP Conway

In [513]:
def round(x) :
    return math.ceil(x)

In [515]:
merged_df['over_no'] = merged_df['over'].apply(round)
merged_df

,match_no,ballnumber,inningno,over,outcome,batter,bowler,comment,score,batsman_score,...,toss_decision,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,man_of_match,over_no
0,1,1,1,0.1,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0,0.0,...,field,Nitin Menon,HAS Khalid,A Bengeri,J Srinath,Gujarat Titans,NaN,5.0,Rashid Khan,1
1,1,2,1,0.2,1lb,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, 1 leg bye,",1,NaN,...,field,Nitin Menon,HAS Khalid,A Bengeri,J Srinath,Gujarat Titans,NaN,5.0,Rashid Khan,1
2,1,3,1,0.3,0,Ruturaj Gaikwad,Mohammed Shami,"Mohammed Shami to Ruturaj Gaikwad, no run,",0,0.0,...,field,Nitin Menon,HAS Khalid,A Bengeri,J Srinath,Gujarat Titans,NaN,5.0,Rashid Khan,1
3,1,4,1,0.4,1,Ruturaj Gaikwad,Mohammed Shami,"Mohammed Shami to Ruturaj Gaikwad, 1 run,",1,1.0,...,field,Nitin Menon,HAS Khalid,A Bengeri,J Srinath,Gujarat Titans,NaN,5.0,Rashid Khan,1
4,1,5,1,0.5,0,Devon Conway,Mohammed Shami,"Mohammed Shami to Devon Conway, no run,",0,0.0,...,field,Nitin Menon,HAS Khalid,A Bengeri,J Srinath,Gujarat Titans,NaN,5.0,Rashid Khan,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17853,74,90,2,14.2,1,Shivam Dube,Mohit Sharma,"Mohit Sharma to Shivam Dube, 1 run,",1,1.0,...,field,Nitin Menon,RJ Tucker,J Madanagopal,J Srinath,Chennai Super Kings,NaN,5.0,DP Conway,15
17854,74,91,2,14.3,1,Ravindra Jadeja,Mohit Sharma,"Mohit Sharma to Ravindra Jadeja, 1 run,",1,1.0,...,field,Nitin Menon,RJ Tucker,J Madanagopal,J Srinath,Chennai Super Kings,NaN,5.0,DP Conway,15
17855,74,92,2,14.4,1,Shivam Dube,Mohit Sharma,"Mohit Sharma to Shivam Dube, 1 run,",1,1.0,...,field,Nitin Menon,RJ Tucker,J Madanagopal,J Srinath,Chennai Super Kings,NaN,5.0,DP Conway,15
17856,74,93,2,14.5,6,Ravindra Jadeja,Mohit Sharma,"Mohit Sharma to Ravindra Jadeja, Six,",6,6.0,...,field,Nitin Menon,RJ Tucker,J Madanagopal,J Srinath,Chennai Super Kings,NaN,5.0,DP Conway,15
17857,74,94,2,14.6,4,Ravindra Jadeja,Mohit Sharma,"Mohit Sharma to Ravindra Jadeja, Four,",4,4.0,...,field,Nitin Menon,RJ Tucker,J Madanagopal,J Srinath,Chennai Super Kings,NaN,5.0,DP Conway,15

In [516]:
def phase(x):
    if x < 6:
        return 'Powerplay'
    elif 6 <= x <= 15:
        return 'Middle'
    elif x >15:
        return 'Death'

In [517]:
merged_df['Phase'] = merged_df['over_no'].apply(phase)
merged_df.tail()

,match_no,ballnumber,inningno,over,outcome,batter,bowler,comment,score,batsman_score,...,umpire1,umpire2,reserve_umpire,match_referee,winner,winner_runs,winner_wickets,man_of_match,over_no,Phase
17853,74,90,2,14.2,1,Shivam Dube,Mohit Sharma,"Mohit Sharma to Shivam Dube, 1 run,",1,1.0,...,Nitin Menon,RJ Tucker,J Madanagopal,J Srinath,Chennai Super Kings,NaN,5.0,DP Conway,15,Middle
17854,74,91,2,14.3,1,Ravindra Jadeja,Mohit Sharma,"Mohit Sharma to Ravindra Jadeja, 1 run,",1,1.0,...,Nitin Menon,RJ Tucker,J Madanagopal,J Srinath,Chennai Super Kings,NaN,5.0,DP Conway,15,Middle
17855,74,92,2,14.4,1,Shivam Dube,Mohit Sharma,"Mohit Sharma to Shivam Dube, 1 run,",1,1.0,...,Nitin Menon,RJ Tucker,J Madanagopal,J Srinath,Chennai Super Kings,NaN,5.0,DP Conway,15,Middle
17856,74,93,2,14.5,6,Ravindra Jadeja,Mohit Sharma,"Mohit Sharma to Ravindra Jadeja, Six,",6,6.0,...,Nitin Menon,RJ Tucker,J Madanagopal,J Srinath,Chennai Super Kings,NaN,5.0,DP Conway,15,Middle
17857,74,94,2,14.6,4,Ravindra Jadeja,Mohit Sharma,"Mohit Sharma to Ravindra Jadeja, Four,",4,4.0,...,Nitin Menon,RJ Tucker,J Madanagopal,J Srinath,Chennai Super Kings,NaN,5.0,DP Conway,15,Middle

In [533]:
venue = merged_df[['venue','location','match_no','inningno','score','over_no','Phase','w']]
venue

,venue,location,match_no,inningno,score,over_no,Phase,w
0,Narendra Modi Stadium,Ahmedabad,1,1,0,1,Powerplay,0
1,Narendra Modi Stadium,Ahmedabad,1,1,1,1,Powerplay,0
2,Narendra Modi Stadium,Ahmedabad,1,1,0,1,Powerplay,0
3,Narendra Modi Stadium,Ahmedabad,1,1,1,1,Powerplay,0
4,Narendra Modi Stadium,Ahmedabad,1,1,0,1,Powerplay,0
...,...,...,...,...,...,...,...,...
17853,Narendra Modi Stadium,Ahmedabad,74,2,1,15,Middle,0
17854,Narendra Modi Stadium,Ahmedabad,74,2,1,15,Middle,0
17855,Narendra Modi Stadium,Ahmedabad,74,2,1,15,Middle,0
17856,Narendra Modi Stadium,Ahmedabad,74,2,6,15,Middle,0
17857,Narendra Modi Stadium,Ahmedabad,74,2,4,15,Middle,0

In [534]:
venue_wise = venue.pivot_table(venue, index=['venue','location','match_no','inningno','over_no','Phase'], aggfunc=sum)
temp = venue_wise.reset_index()
temp

,venue,location,match_no,inningno,over_no,Phase,score,w
0,Arun Jaitley Stadium,Delhi,7,1,1,Powerplay,11,0
1,Arun Jaitley Stadium,Delhi,7,1,2,Powerplay,9,0
2,Arun Jaitley Stadium,Delhi,7,1,3,Powerplay,9,1
3,Arun Jaitley Stadium,Delhi,7,1,4,Powerplay,4,0
4,Arun Jaitley Stadium,Delhi,7,1,5,Powerplay,9,1
...,...,...,...,...,...,...,...,...
2868,Wankhede Stadium,Mumbai,69,2,14,Middle,8,1
2869,Wankhede Stadium,Mumbai,69,2,15,Middle,4,0
2870,Wankhede Stadium,Mumbai,69,2,16,Death,20,0
2871,Wankhede Stadium,Mumbai,69,2,17,Death,13,0
2872,Wankhede Stadium,Mumbai,69,2,18,Death,8,0

In [544]:
nms_phase = temp.pivot_table(values=['score','w'], index = ['location','venue'], columns =['inningno','Phase'], aggfunc=sum)
nms_phase

                                                              score         \
inningno                                                          1
Phase                                                         Death Middle
location   venue
Ahmedabad  Narendra Modi Stadium                                527    853
Bengaluru  M Chinnaswamy Stadium                                408    674
Chandigarh Punjab Cricket Association IS Bindra Stadium         288    458
Chennai    MA Chidambaram Stadium                               425    725
Delhi      Arun Jaitley Stadium                                 365    579
Dharamsala Himachal Pradesh Cricket Association Stadium         135    169
Guwahati   Barsapara Cricket Stadium                            114    163
Hyderabad  Rajiv Gandhi International Stadium                   345    562
Jaipur     Sawai Mansingh Stadium                               237    402
Kolkata    Eden Gardens                                         400    635
Lucknow    Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cr...   350    463
Mumbai     Wankhede Stadium                                     415    624

                                                                               \
inningno                                                                    2
Phase                                                         Powerplay Death
location   venue
Ahmedabad  Narendra Modi Stadium                                    374   352
Bengaluru  M Chinnaswamy Stadium                                    286   310
Chandigarh Punjab Cricket Association IS Bindra Stadium             243   173
Chennai    MA Chidambaram Stadium                                   380   365
Delhi      Arun Jaitley Stadium                                     285   242
Dharamsala Himachal Pradesh Cricket Association Stadium              96   118
Guwahati   Barsapara Cricket Stadium                                119    97
Hyderabad  Rajiv Gandhi International Stadium                       314   306
Jaipur     Sawai Mansingh Stadium                                   220   156
Kolkata    Eden Gardens                                             315   305
Lucknow    Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cr...       223   187
Mumbai     Wankhede Stadium                                         345   292

                                                                      \
inningno
Phase                                                         Middle
location   venue
Ahmedabad  Narendra Modi Stadium                                 773
Bengaluru  M Chinnaswamy Stadium                                 718
Chandigarh Punjab Cricket Association IS Bindra Stadium          471
Chennai    MA Chidambaram Stadium                                632
Delhi      Arun Jaitley Stadium                                  542
Dharamsala Himachal Pradesh Cricket Association Stadium          186
Guwahati   Barsapara Cricket Stadium                             157
Hyderabad  Rajiv Gandhi International Stadium                    590
Jaipur     Sawai Mansingh Stadium                                374
Kolkata    Eden Gardens                                          572
Lucknow    Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cr...    414
Mumbai     Wankhede Stadium                                      714

                                                                            w  \
inningno                                                                    1
Phase                                                         Powerplay Death
location   venue
Ahmedabad  Narendra Modi Stadium                                    387    24
Bengaluru  M Chinnaswamy Stadium                                    285    15
Chandigarh Punjab Cricket Association IS Bindra Stadium             223    11
Chennai    MA Chidambaram Stadium                                   404    28
Delhi      Arun Jaitley Stadium                                     337    18
Dharamsala Himachal Pradesh Cricket Association Stadium              82     0
Guwahati   Barsapara Cricket Stadium                                 80     4
Hyderabad  Rajiv Gandhi International Stadium                       233    15
Jaipur     Sawai Mansingh Stadium                                   179    11
Kolkata    Eden Gardens                                             325    17
Lucknow    Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cr...       238    19
Mumbai     Wankhede Stadium                                         346    18

                                                                      \
inningno
Phase                                                         Middle
location   venue
Ahmedabad  Narendra Modi Stadium                                  15
Bengaluru  M Chinnaswamy Stadium                                  19
Chandigarh Punjab Cricket Association IS Bindra Stadium            9
Chennai    MA Chidambaram Stadium                                 26
Delhi      Arun Jaitley Stadium                                   21
Dharamsala Himachal Pradesh Cricket Association Stadium            5
Guwahati   Barsapara Cricket Stadium                               4
Hyderabad  Rajiv Gandhi International Stadium                     21
Jaipur     Sawai Mansingh Stadium                                 16
Kolkata    Eden Gardens                                           17
Lucknow    Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cr...     22
Mumbai     Wankhede Stadium                                       22

                                                                               \
inningno                                                                    2
Phase                                                         Powerplay Death
location   venue
Ahmedabad  Narendra Modi Stadium                                     11    22
Bengaluru  M Chinnaswamy Stadium                                      6    18
Chandigarh Punjab Cricket Association IS Bindra Stadium               5    13
Chennai    MA Chidambaram Stadium                                     9    16
Delhi      Arun Jaitley Stadium                                       9    14
Dharamsala Himachal Pradesh Cricket Association Stadium               2     7
Guwahati   Barsapara Cricket Stadium                                  0     5
Hyderabad  Rajiv Gandhi International Stadium                        12    12
Jaipur     Sawai Mansingh Stadium                                     2     8
Kolkata    Eden Gardens                                              11    11
Lucknow    Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cr...         6    16
Mumbai     Wankhede Stadium                                           5     9


inningno
Phase                                                         Middle Powerplay
location   venue
Ahmedabad  Narendra Modi Stadium                                  28        15
Bengaluru  M Chinnaswamy Stadium                                  16        12
Chandigarh Punjab Cricket Association IS Bindra Stadium           12        10
Chennai    MA Chidambaram Stadium                                 30        12
Delhi      Arun Jaitley Stadium                                   19         7
Dharamsala Himachal Pradesh Cricket Association Stadium            5         2
Guwahati   Barsapara Cricket Stadium                               7         4
Hyderabad  Rajiv Gandhi International Stadium                     19         8
Jaipur     Sawai Mansingh Stadium                                 17         4
Kolkata    Eden Gardens                                           21         9
Lucknow    Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cr...     20         8
Mumbai     Wankhede Stadium                                       13        10